import { fontClash, fontTeachers } from './fonts';
import type { Metadata } from 'next';
import './styles.css';
import { Toaster } from '@mjs/ui/primitives/sonner';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { getLocale } from 'next-intl/server';

import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [locale, messages] = await Promise.all([getLocale(), getMessages()]);
  return (
    <html lang={locale}>
      <body
        className={`${fontClash.variable} ${fontTeachers.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </NextIntlClientProvider>
        <Toaster
          position='top-center'
          offset={10}
          toastOptions={{ duration: 2000 }}
        />
      </body>
    </html>
  );
}
